### ISSUE TITLE
[FAQ] is this project dead

### ISSUE THREAD

**Issue by kirantpatil** [rubyists/tiny_call_center#3]
I don't see any updates for this project.

So is this dead ?

What are the other alternative to setup callcenter with freeswitch ?

Ex: http://adhearsion.com/

Thanks.

**Comment by OpenSourceAlchemist** [comment]
I'd say it probably is.  None of us work in call center environments anymore, so we don't have a good environment to really work with it to even test now.

**Comment by kirantpatil** [comment]
Thanks.
